workspace/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :salons
  root :to => "salons#index"

end

workspace/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

workspace/app/models/salon.rb
class Salon < ActiveRecord::Base
end

workspace/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

workspace/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

workspace/app/controllers/salons_controller.rb
class SalonsController < ApplicationController
  before_action :set_salon, only: [:show, :edit, :update, :destroy]

  # GET /salons
  # GET /salons.json
  def index
    @salons = Salon.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /salons/1
  # GET /salons/1.json
  def show
  end

  # GET /salons/new
  def new
    @salon = Salon.new
  end

  # GET /salons/1/edit
  def edit
  end

  # POST /salons
  # POST /salons.json
  def create
    @salon = Salon.new(salon_params)

    respond_to do |format|
      if @salon.save
        format.html { redirect_to @salon, notice: 'Dodano nowy samochód.' }
        format.json { render :show, status: :created, location: @salon }
      else
        format.html { render :new }
        format.json { render json: @salon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salons/1
  # PATCH/PUT /salons/1.json
  def update
    respond_to do |format|
      if @salon.update(salon_params)
        format.html { redirect_to @salon, notice: 'Dane samochodu zostały zaktualizowane.' }
        format.json { render :show, status: :ok, location: @salon }
      else
        format.html { render :edit }
        format.json { render json: @salon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salons/1
  # DELETE /salons/1.json
  def destroy
    @salon.destroy
    respond_to do |format|
      format.html { redirect_to salons_url, notice: 'Samochód został usunięty z salonu.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salon
      @salon = Salon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def salon_params
      params.require(:salon).permit(:nazwa, :rocznik, :przebieg, :cena)
    end
end

workspace/app/helpers/application_helper.rb
module ApplicationHelper
end

workspace/app/helpers/salons_helper.rb
module SalonsHelper
end

workspace/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Salon samochodowy - Szymon zawodny - Zaliczenie ASI', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar">
    <!--<li><%= link_to 'Strona główna', root_path %></li>-->
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'Edytuj profil', edit_user_registration_path %></li>
          <li><%= link_to 'Wyloguj', destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to 'Zaloguj', new_user_session_path %></li>
          <li><%= link_to 'Zarejestruj', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

workspace/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Salon samochodowy</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
      
      <%= yield %>
    </div>
  
  </body>

</html>

workspace/app/views/salons/_form.html.erb
<%= form_for(salon) do |f| %>
  <% if salon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(salon.errors.count, "error") %> prohibited this salon from being saved:</h2>

      <ul>
      <% salon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nazwa %>
    <%= f.text_field :nazwa %>
  </div>

  <div class="field">
    <%= f.label :rocznik %>
    <%= f.text_field :rocznik %>
  </div>

  <div class="field">
    <%= f.label :przebieg %>
    <%= f.text_field :przebieg %>
  </div>

  <div class="field">
    <%= f.label :cena %>
    <%= f.text_field :cena %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

workspace/app/views/salons/edit.html.erb
<% if user_signed_in? %>
<h1>Zmień dane samochodu</h1>

<%= render 'form', salon: @salon %>
<% else  %>
	 <h5> <u>Aby wprowadzić zmiany musisz być zalogowany</u> </h5>
<% end %>
<button class="btn btn-warning" type="button"><%= link_to 'Wyświetl', @salon %></button> |
<button class="btn btn-info" type="button"><%= link_to 'Wróć', salons_path %></button>

workspace/app/views/salons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Salon samochodowy</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nazwa</th>
      <th>Rocznik</th>
      <th>Przebieg</th>
      <th>Cena</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @salons.each do |salon| %>
      <tr>
        <td><%= salon.nazwa %></td>
        <td><%= salon.rocznik %></td>
        <td><%= salon.przebieg %></td>
        <td><%= salon.cena %></td>
        <td><button class="btn btn-info" type="button"><%= link_to 'Szczegóły', salon %></button></td>
        <td><button class="btn btn-warning" type="button"><%= link_to 'Edytuj', edit_salon_path(salon) %></button></td>
        <% if user_signed_in? %>
        <td><button class="btn btn-danger" type="button"><%= link_to 'Usuń', salon, method: :delete, data: { confirm: 'Na pewno chcesz usunąć?' } %></button></td>
        <% else  %>
	      
        <% end %>
        
      </tr>
    <% end %>
  </tbody>
</table>
<center>
<p align="center"><%= will_paginate @salons %></p>
</center>

<br>

<button class="btn btn-success" type="button"><%= link_to 'Dodaj nowy samochód', new_salon_path %></button>

workspace/app/views/salons/new.html.erb
<% if user_signed_in? %>
<h1>Dodaj nowy samochód do salonu</h1>

<%= render 'form', salon: @salon %>
<% else  %>
	<h5> <u>Aby wprowadzić nowy samochód musisz być zalogowany</u> </h5>
<% end %>

<button class="btn btn-info" type="button"><%= link_to 'Wróc', salons_path %></button>

workspace/app/views/salons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nazwa:</strong>
  <%= @salon.nazwa %>
</p>

<p>
  <strong>Rocznik:</strong>
  <%= @salon.rocznik %>
</p>

<p>
  <strong>Przebieg:</strong>
  <%= @salon.przebieg %>
</p>

<p>
  <strong>Cena:</strong>
  <%= @salon.cena %>
</p>
<button class="btn btn-warning" type="button"><%= link_to 'Zmień', edit_salon_path(@salon) %></button> |
<button class="btn btn-info" type="button"><%= link_to 'Wróć', salons_path %></button>