workspace-heroku/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :auto_handels
  root :to => "auto_handels#index"

end

workspace-heroku/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

workspace-heroku/app/models/auto_handel.rb
class AutoHandel < ActiveRecord::Base
end

workspace-heroku/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

workspace-heroku/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

workspace-heroku/app/controllers/auto_handels_controller.rb
class AutoHandelsController < ApplicationController
  before_action :set_auto_handel, only: [:show, :edit, :update, :destroy]

  # GET /auto_handels
  # GET /auto_handels.json
  def index
    @auto_handels = AutoHandel.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /auto_handels/1
  # GET /auto_handels/1.json
  def show
  end

  # GET /auto_handels/new
  def new
    @auto_handel = AutoHandel.new
  end

  # GET /auto_handels/1/edit
  def edit
  end

  # POST /auto_handels
  # POST /auto_handels.json
  def create
    @auto_handel = AutoHandel.new(auto_handel_params)

    respond_to do |format|
      if @auto_handel.save
        format.html { redirect_to @auto_handel, notice: 'Auto handel was successfully created.' }
        format.json { render :show, status: :created, location: @auto_handel }
      else
        format.html { render :new }
        format.json { render json: @auto_handel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auto_handels/1
  # PATCH/PUT /auto_handels/1.json
  def update
    respond_to do |format|
      if @auto_handel.update(auto_handel_params)
        format.html { redirect_to @auto_handel, notice: 'Auto handel was successfully updated.' }
        format.json { render :show, status: :ok, location: @auto_handel }
      else
        format.html { render :edit }
        format.json { render json: @auto_handel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auto_handels/1
  # DELETE /auto_handels/1.json
  def destroy
    @auto_handel.destroy
    respond_to do |format|
      format.html { redirect_to auto_handels_url, notice: 'Auto handel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auto_handel
      @auto_handel = AutoHandel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auto_handel_params
      params.require(:auto_handel).permit(:marka, :model, :cena)
    end
end

workspace-heroku/app/helpers/application_helper.rb
module ApplicationHelper
end

workspace-heroku/app/helpers/auto_handels_helper.rb
module AutoHandelsHelper
end

workspace-heroku/app/views/auto_handels/_form.html.erb
<%= form_for(auto_handel) do |f| %>
  <% if auto_handel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(auto_handel.errors.count, "error") %> prohibited this auto_handel from being saved:</h2>

      <ul>
      <% auto_handel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :marka %>
    <%= f.text_field :marka %>
  </div>

  <div class="field">
    <%= f.label :model %>
    <%= f.text_field :model %>
  </div>

  <div class="field">
    <%= f.label :cena %>
    <%= f.text_field :cena %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

workspace-heroku/app/views/auto_handels/edit.html.erb
<h1>Editing Auto Handel</h1>

<%= render 'form', auto_handel: @auto_handel %>

<%= link_to 'Show', @auto_handel %> |
<%= link_to 'Back', auto_handels_path %>

workspace-heroku/app/views/auto_handels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Auto Handels</h1>

<table class="table table-responsive table-hover">
  <thead>
    <tr>
      <th>Marka</th>
      <th>Model</th>
      <th>Cena</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @auto_handels.each do |auto_handel| %>
      <tr>
        <td><%= auto_handel.marka %></td>
        <td><%= auto_handel.model %></td>
        <td><%= auto_handel.cena %></td>
        <td><%= link_to 'Show', auto_handel %></td>
        <% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_auto_handel_path(auto_handel) %></td>
        <td><%= link_to 'Destroy', auto_handel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else  %>
        <td>Please log in to update and delete <td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<center>
  <%= will_paginate @auto_handels %>
  
</center>

<br>

<%= link_to 'New Auto Handel', new_auto_handel_path %>

workspace-heroku/app/views/auto_handels/new.html.erb
<% if user_signed_in? %>
<h1>New Auto Handel</h1>

<%= render 'form', auto_handel: @auto_handel %>
<% else  %>
	<h5> <u>Aby wprowadzić nowy samochód musisz być zalogowany</u> </h5>
<% end %>

<%= link_to 'Back', auto_handels_path %>

workspace-heroku/app/views/auto_handels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Marka:</strong>
  <%= @auto_handel.marka %>
</p>

<p>
  <strong>Model:</strong>
  <%= @auto_handel.model %>
</p>

<p>
  <strong>Cena:</strong>
  <%= @auto_handel.cena %>
</p>

<%= link_to 'Edit', edit_auto_handel_path(@auto_handel) %> |
<%= link_to 'Back', auto_handels_path %>

workspace-heroku/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Auto-Handel - Szymon zawodny - Zaliczenie ASI', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar">
    <!--<li><%= link_to 'Main Site', root_path %></li>-->
     
     
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Register', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

workspace-heroku/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Auto-Handel</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
      
      <%= yield %>
    </div>
  
  </body>

</html>